#!/bin/bash
# To use this script, run: source ./init.sh

# -------------------------------------
#
# User bashrc init
#
# -------------------------------------

BASHRC="$HOME/.bashrc"
BACKUP="$BASHRC.bak"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$SRC_DIR/scripts"
START_MARKER="# >>> CUSTOM_CONFIG_START (Do not edit inside this block) <<<"
END_MARKER="# >>> CUSTOM_CONFIG_END <<<"

# 3. Handle Backup (Remove old, create new)
if [ -f "$BACKUP" ]; then
    rm "$BACKUP"
    echo "Removed old backup: $BACKUP"
fi

if [ -f "$BASHRC" ]; then
    cp "$BASHRC" "$BACKUP"
    echo "Created new backup: $BACKUP"
else
    touch "$BASHRC"
    echo "Created new empty .bashrc"
fi

# 2. Check if the Markers exist. If not, append them to the end of the file.
if ! grep -q "$START_MARKER" "$BASHRC"; then
    echo "" >>"$BASHRC"
    echo "$START_MARKER" >>"$BASHRC"
    echo "$END_MARKER" >>"$BASHRC"
    echo "Markers initialized in .bashrc"
fi

INJECT_CONTENT=$(
    cat <<EOF
# Auto-generated by init.sh.
# Dynamically loads all .sh files from: $SCRIPTS_DIR

if [ -d "$SCRIPTS_DIR" ]; then
    for script in "$SCRIPTS_DIR"/*.sh; do
        # Check if file is readable
        if [ -r "\$script" ]; then
            . "\$script"
        fi
    done
fi
EOF
)

NEW_BASHRC=$(mktemp)

sed -n "1,/$START_MARKER/p" "$BASHRC" >"$NEW_BASHRC"
echo "$INJECT_CONTENT" >>"$NEW_BASHRC"
sed -n "/$END_MARKER/,\$p" "$BASHRC" >>"$NEW_BASHRC"

# 7. Finalize
mv -f "$NEW_BASHRC" "$BASHRC"

echo "Success! .bashrc updated."

# 8. Source the file
# Note: This only affects the current terminal if the script itself is sourced.
# source a.sh / . a.sh both run in current shell env aka terminal shell
# ./a.sh not it runs in subshell
. "$BASHRC"
echo "Refreshed .bashrc in this session."
